### ISSUE TITLE
Issue while using QnA Maker integration

### ISSUE THREAD

**Issue by rkm050288** [microsoft/BotFramework-Composer#2344]
I am getting error "Object reference not set to an instance of an object.", when I use QnA maker with unknown intent trigger as per [documentation ](https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot)

![image](https://user-images.githubusercontent.com/38185096/77360789-e88dce80-6d45-11ea-806f-e9bbb22bf8c5.png)

Kindly check and let me know what is the issue.

**Comment by hibrenda** [comment]
@rkm050288 please add "=" for your settings. 
![image](https://user-images.githubusercontent.com/43408889/77664108-d4053c80-6fb8-11ea-8abf-f2c10bf3f4ee.png)

If that does not work, please let us know.

**Comment by rkm050288** [comment]
Thanks, This worked, can this be updated in the guides as well ?

**Comment by hibrenda** [comment]
@rkm050288 yes. we will updated it later. thanks .

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2405

**Comment by HimajaKRNttData** [comment]
> @rkm050288 please add "=" for your settings.
> ![image](https://user-images.githubusercontent.com/43408889/77664108-d4053c80-6fb8-11ea-8abf-f2c10bf3f4ee.png)
> 
> If that does not work, please let us know.

@hibrenda this didnt work for me. I have faced the same issue.

**Comment by hibrenda** [comment]
@HimajaKRNttData what error you hit ? If you installed  latest composer , this should work.

**Comment by HimajaKRNttData** [comment]
@hibrenda, "Object reference not set to an instance of an object." This is the error i'm facing when i try to access QnA KB from the composer. I even tried adding '='  in the settings but it didn't resolve the issue. Also, I have the latest composer installed.

**Comment by hibrenda** [comment]
- make sure you set the correct content in setting page
- make sure no any other steps in case errors exist in other steps.
- after that if error still prompts, you can try this https://github.com/microsoft/BotFramework-Composer/issues/2941#issuecomment-625805892. But actually this is not must have with latest master. so I don't think this introduced by this if you are using latest composer.

**Comment by HimajaKRNttData** [comment]
Thank you @hibrenda for helping with this error. It is resolved now.

**Comment by zxyanliu** [comment]
@hibrenda is there anything I should update in the [doc](https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot)?

**Comment by Prerana-acce** [comment]
Hi! Is there a way to extract source and all three answers from QnADialog using Bot Composer? There is not enough information about it. Any help would be highly appreciated!
