### ISSUE TITLE
Publish to Azure Web App - never completes

### ISSUE THREAD

**Issue by drfbwilliams** [microsoft/BotFramework-Composer#4746]
## Describe the bug

With a stripped down publishing profile, the composer publish never completes. Status continues circling with a message of Accepted for publishing.

See Log - only shows the message "Log Output" - nothing else

## Version

Release: 1.1.1

## Browser

- [ x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a sample echo bot in composer
2. Provision a bot in Azure using the echo bot template - creating a new resource group
3. Using everything as default in both composer and in Azure - complete the publishing template, removing all settings fields except for password and id
4. Publish with the profile

## Expected behavior

The publish to complete or an error stating why. I expected a log file that could show the steps taken.

## Screenshots

![image](https://user-images.githubusercontent.com/69192966/98704185-ee0c5780-23ae-11eb-87cf-7d2ca80889fe.png)

## Additional context

In my example, I named a provision in Azure that is different from the bot name. For example, the service could be called:

 my-bots.azurewebsites.net

but the actual unique bot could be named:

test-bot

in this case, using the template "name" and "environment" would fail. I understand there is a "hostname" settings field available, but nowhere do I see what that should be. Can you please explain based on the above example, and, does that completely override the -dev name fields.

**Comment by zxyanliu** [comment]
The error **was not reproduced** with an EchoBot created using the [main branch build](https://github.com/microsoft/BotFramework-Composer) as of Nov 10, 2020. 

![image](https://user-images.githubusercontent.com/32497439/98748898-7965f880-236f-11eb-8cfe-589b684cc4d4.png)

**Tested in WebChat in Azure:** 

![image](https://user-images.githubusercontent.com/32497439/98748930-8c78c880-236f-11eb-866f-aee18af5d525.png)

**Comment by drfbwilliams** [comment]
Can  you please confirm the details of the publish config file as that appears to be the issue.

**Comment by drfbwilliams** [comment]
@cwhitten - I am trying to muster some positive review here for you, but I am struggling due to the issues I face with the solution publish function.

With respect to Composer, I had created the same type of solution several years ago in WPF called AIStudio. Same workflows, same concepts, interruptions, rest calls etc - so for the task of creating fundamentally simple chatbots and script line conversation flows, I too think this is the best approach for broad editing by non-technical users. I had many more complex use cases to implement along with keystone personalities which makes flow architecture even more complex, but where you are at now - great! The solution looks like it is heading in the right direction (possibly some serious gotcha's to come, but see where you take it first)

I am at the moment looking at the specification of around 60 bots. I have some stupidly complex work flows to achieve, so by all means, allow me to be a guinea pig and help you deliver a better product, with the benefit of my previous experiences, if they can help.

So where are we? I'm sorry, but this publishing flow is a complete mess.

When I look at docs like this:
https://docs.microsoft.com/en-us/composer/how-to-publish-bot#deploy-to-existing-azure-resources

The specification of fields is inconsistent at best. E.g. The hostname field is at one point specified as such:
"hostname": "**NAME OF THE HOST**",

then later in the same document as:
"hostname": "**your web app name**",

Which one is it? What is the exact format? - the word "host" normally assumes an entire URL, but is this just the app service name?

Why is the field name "name" not called resourcegroupname? That would clarify it.

When I create a new publish profile in composer, it is described as this:
  "name": "**unique name in your subscription**",



When applying this instruction:
![image](https://user-images.githubusercontent.com/69192966/98769985-bc79a780-2413-11eb-8f55-093db540a5fc.png)

If you edit the profile in composer, all the pre-existing pollution of non-required settings of LUIS and Telemetry etc are all added back in. Why? I would expect MY configuration to be as created.


Quite clearly, a background service is running to attempt the publish, but it just sits and spins. Even if you delete the profile, that process continues -- I have no idea if that is blocking any new profile edit / retry attempts to publish?

If I create a new profile and use the same name as before, magically all of the past publish attempts show up. They should be all killed and removed immediately on me deleting that profile. Is this a known issue?


Perhaps one of the biggest issues is making users hunt for an azure access key, then create new credentials (if you find that spot), then get some other value from another screen etc - the process is ripe for user errors in this copy/paste world, and because of the information missalignment, the user (me in this case) has no idea what setting/field value is causing the publish to fail.

**Having only successfully published once** in the last 12 hours with a crazy number of configurations - I was then greeted with a non-functioning (**default echo bot from composer**) which I then have to navigate to another page to be given an entirely unhelpful error message:
![image](https://user-images.githubusercontent.com/69192966/98770390-b506ce00-2414-11eb-9e98-48d749f2549c.png)

Certainly not helped by a bot emulator that then freezes when being used in debug mode.

Please don't read any of this as an attack of criticism of the work being done - I'm rooting for your team and I just want it too all work so more people can use the products and services.

Any help - logs I can gather etc, just ask,

In the meantime, some deep looking into these publishing issues would help me (and possibly others) enormously.

Many thanks
Brennon

**Comment by zxyanliu** [comment]
Hi @drfbwilliams thanks for your patience. 

* The error was not reproduced when I tested publishing a bot with newly provisioned Azure resources (using scripts).
* The error was reproduced when I tested publishing a bot to existing Azure resources (manually created). 

  ![MicrosoftTeams-image (16)](https://user-images.githubusercontent.com/32497439/98783852-0ed4ad00-23af-11eb-9879-e1749767d96a.png)

* The error was resolved after I restarted Composer and built a new bot. It seems that if you fail one time and try again, this process will never complete. 

   ![image](https://user-images.githubusercontent.com/32497439/98783927-2d3aa880-23af-11eb-9422-7fab273cc8d4.png)

   ![image](https://user-images.githubusercontent.com/32497439/98784147-86a2d780-23af-11eb-88fa-d9403b1234e1.png)

Thanks again for your feedback.

**Comment by drfbwilliams** [comment]
@zxyanliu thanks for your response.

In reading your results, it does not appear to be viable to have to rebuild a new bot every time this happens. Or are you stating that the existing bot project must be "rebuilt"?

As per the original comments, can you please confirm or provide a sample of the field values for those of us who have a resource group not named with -dev as well as a web bot app that is named differently from the parent app service.

Many thanks,
Brennon

**Comment by luhan2017** [comment]
@drfbwilliams ， Here is the code logic of how to present web bot app hostname. 
1. if hostname exists, just use it regardless of name and environment.
2. if hostname not exists, check if environement is null or empty, if yes, just use name, otherwise use name-environment. 

Please try with the above setting. We will investigate on why never ends and no error message shown in the log. 
Thanks for reporting.

**Comment by drfbwilliams** [comment]
Thanks for the follow up - this is the only format that I can consistently verify works:

`{
  "accessToken": "<<token>>",
"name": "<<resource group name>>",
"hostname": "<<web app name only i.e. my-new-bot>>",
  "settings": {
    "MicrosoftAppId": "<<app id>>",
    "MicrosoftAppPassword": "<<password>>"
  }
}
`

I still have a failing bot at the end of it. I will created a scripted provision today and try and understand what the key differences are that cause this.

Shall close this as resolved. Thanks.
