### ISSUE TITLE
"Replace Dialog" action doesn't find existing dialog in 2.1

### ISSUE THREAD

**Issue by Clooney24** [microsoft/BotFramework-Composer#8538]
I was using a Replace Dialog action before in 1.4 that worked without problems. 

In 2.1, I get this error message. (Dialog is named "Restart")

"DialogContext.BeginDialogAsync(): A dialog with an id of 'Restart' wasn't found. The dialog must be included in the current or parent DialogSet. For example, if subclassing a ComponentDialog you can call AddDialog() within your constructor."

The dialog was selected with that dropdown selector, so a misspelling can be excluded.

I tried to use "Begin Dialog" action with same dialog just to see what happens and this worked fine. So error is propably somewhere in ReplaceDialog logic.

Maybe a hint: The error texts mentioned "id" but selection is by name not by id.

Version:  2.1.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by tonyanziano** [comment]
@anusharr can you please try to reproduce this? It seems like the issue is that the "Replace Dialog" is not functioning properly when selecting a target dialog from the "Dialog name" dropdown.

**Comment by anusharr** [comment]
@Clooney24, can you provide screenshots of your implementation along with the code (using the `Show code` option at the top right of the authoring canvas)? I am able to get the `Replace this dialog` working in v2.1.0.

**Comment by Clooney24** [comment]
ok, here the UI:

![image](https://user-images.githubusercontent.com/14079908/128991415-4dcd4db8-b7b5-447c-aee5-a97b33ee1e93.png)

code of the action call:

`                {
                  "value": "/reset",
                  "actions": [
                    {
                      "$kind": "Microsoft.SetProperty",
                      "$designer": {
                        "id": "SSmuW8"
                      },
                      "property": "conversation.restartCode",
                      "value": "=dialog.parameter+\" \"+dialog.parameter2"
                    },
                    {
                      "$kind": "Microsoft.ReplaceDialog",
                      "$designer": {
                        "id": "acKREH"
                      },
                      "activityProcessed": false,
                      "dialog": "Restart",
                      "options": {
                        "doReset": "yes"
                      }
                    }
                  ]
                }
`


here UI of "Restart" dialog:

![image](https://user-images.githubusercontent.com/14079908/128994523-3bfe831b-c143-456f-a9d0-f7e01cf57b81.png)

and partial code of the "Restart" dialog (removed the triggers part)

`{
  "$kind": "Microsoft.AdaptiveDialog",
  "$designer": {
    "id": "hpMnvG",
    "name": "Restart",
    "description": ""
  },
  "autoEndDialog": true,
  "defaultResultProperty": "dialog.result",
  "triggers": [ ( ** hidden for sample **) ],
  "generator": "Restart.lg",
  "recognizer": "Restart.lu.qna",
  "id": "Restart"
}
`

what I'm missing in the code is that input key "doReset" that is defined in block Dialog Interface. Don't know where Composer stores this information?

**Comment by cpolanish** [comment]
I'm having the same issue. It seems to be specific to one particular dialog I'm trying to get into. If I switch the action to another dialog just to test it works fine.

**Comment by anusharr** [comment]
@Clooney24, can you attach a screenshot of your project pane. I am able to get the `DialogContext.BeginDialogAsync(): A dialog with an id of ' ' wasn't found.` error when I try to create a dialog of my own and link it to the `Replace this dialog` action, but the issue gets resolved if I add a trigger under the main dialog and connect it to the dialog I am linking in the `Replace this dialog` action.

@cpolanish, can you elaborate more on your implementation(screenshots, steps to reproduce, etc.)?

**Comment by cpolanish** [comment]
Sure, see below:

You can see I have a replace dialog action configured to go to the dialog "findCallerByName". This step is inside the "findCallerByPhone" dialog.
![image](https://user-images.githubusercontent.com/42741799/129357754-7b4a3a4b-d4a2-4cf5-8018-20b4725744a8.png)

Here's the code for that action
`{
  "$kind": "Microsoft.ReplaceDialog",
  "$designer": {
    "id": "WV19tb"
  },
  "activityProcessed": true,
  "dialog": "findCallerByName"
},`

And here's the code for the dialog:
`{
  "$kind": "Microsoft.AdaptiveDialog",
  "$designer": {
    "id": "KUV7aW",
    "name": "findCallerByName",
    "description": "Find a caller by prompting for client name and first/last nam"
  },
  "autoEndDialog": true,
  "defaultResultProperty": "dialog.result",
  "triggers": [
    {
      "$kind": "Microsoft.OnBeginDialog",
      "$designer": {
        "name": "BeginDialog",
        "description": "",
        "id": "hff0EU"
      },
      "actions": [
        ...
      ]
    },
    {
      "$kind": "Microsoft.OnDialogEvent",
      "$designer": {
        "id": "jIzycn",
        "name": "Store Phone"
      },
      "event": "StorePhone",
      "actions": [
        ...
      ]
    }
  ],
  "generator": "findCallerByName.lg",
  "recognizer": "findCallerByName.lu.qna",
  "id": "findCallerByName"
}`

This was working fine until recently where we just happened to notice during testing we were getting the error:
> DialogContext.BeginDialogAsync(): A dialog with an id of ‘findCallerByName’ wasn’t found. The dialog must be included in the current or parent DialogSet. For example, if subclassing a ComponentDialog you can call AddDialog() within your constructor.

You don't have to do anything special, just let the bot get to that action. Like I mentioned, oddly, other replace dialog actions pointing to the same "findCallerByName" dialog that are in other dialogs work fine, and changing this particular action to point to a different dialog also works fine, it just seems to be the combination of pointing to "findCallerByName" from the "findCallerByPhone" dialog that is having an issue. I tried recreating the action and still get the same result.

**Comment by anusharr** [comment]
@cpolanish, apologize for the delay in response. Can you specify more on the part where your above implementation was working fine and then you started to get the error. Did you make any other changes after which the error started showing up?

**Comment by cpolanish** [comment]
I did not, only thing that changed was I upgraded to 2.1 (at least to the best of my knowledge). Unfortunately I ended up scrapping that bot and have rebuilt it (had a handful of random issues I was facing, figured it was better to just start fresh), but still happy to provide whatever insight I can.


Christopher Polanish
Software Team Lead
(631) 815-1711
***@***.***
flexiblesystems.com
This e-mail and any files transmitted with it are intended only for the person or entity to which it is addressed and may contain confidential material and/or material protected by law. Any retransmission or use of this information may be a violation of that law. If you received this in error, please contact the sender and delete the material from any computer.

**Comment by Clooney24** [comment]
> @Clooney24, can you attach a screenshot of your project pane. I am able to get the `DialogContext.BeginDialogAsync(): A dialog with an id of ' ' wasn't found.` error when I try to create a dialog of my own and link it to the `Replace this dialog` action, but the issue gets resolved if I add a trigger under the main dialog and connect it to the dialog I am linking in the `Replace this dialog` action.
> 
> @cpolanish, can you elaborate more on your implementation(screenshots, steps to reproduce, etc.)?

What do you mean by "add a trigger under the main dialog and connect it to the dialog"? How did you connect the dialog to the trigger? I have a trigger in the main dialog with another Replace dialog action to same dialog, but this didn't resolve this issue.

**Comment by Clooney24** [comment]
This is really urgent, we need to migrate to 2.1 quickly because of some other features, but we can't until this issue is resolved.

**Comment by Clooney24** [comment]
@anusharr I'm happy to offer a screen-sharing session if that helps.

**Comment by anusharr** [comment]
Adding @boydc2014 for any further clarifications.

@Clooney24 @cpolanish, since the Replace Dialog action was working in v1.4, it seems be a regression on the SDK side. A quick workaround at this point would be to add ` "dialogs" : ["the dialog name which is configured in the Replace dialog action "]` to the main dialog code to manually link the dialog to the main dialog . Let me attach screenshots of the repro I tried on my end to make it work for a better understanding:

![image](https://user-images.githubusercontent.com/48731427/130709437-2521d7a1-a5ef-42fd-9914-0ec7f56b9290.png)

![image](https://user-images.githubusercontent.com/48731427/130709470-02f105b5-5df6-462d-b495-2ff45154d2ca.png)

![image](https://user-images.githubusercontent.com/48731427/130709632-c51d8d62-a72f-4ecc-ba8d-0735572ef098.png)

![image](https://user-images.githubusercontent.com/48731427/130709758-58a0c2f2-a769-412b-8964-e38548566d5a.png)

 Please give this a try and let me know if it unblocks you. I will update the thread once I have more info on the fix.

**Comment by Clooney24** [comment]
Hi @anusharr,

thanks for this informations, but this workaround doesn't work and shows a very strange behaviour.


First, I get a warning "Property dialogs is not allowed": 

![image](https://user-images.githubusercontent.com/14079908/130826628-a0dc427a-0e17-4983-a050-278a091a7cb0.png)


When I start anyway and test the ReplaceDialog calling the "Restart" dialog, I got an error that references to id "Restart2". In my whole application there is no id "Restart2".

![image](https://user-images.githubusercontent.com/14079908/130826822-c4623209-3331-4e10-94cc-e05957de2a7a.png)

**Comment by Clooney24** [comment]
here a stacktrace, looks that there are some iterations, as ReplaceDialog is called several times? 
(LocaleSelection, ActivityLogger and ProactiveMessaging are our custom components)

[18:21:42 ERR] ----- ERROR: 'DialogContext.BeginDialogAsync(): A dialog with an id of 'Restart' wasn't found. The dialog must be included in the current or parent DialogSet. For example, if subclassing a ComponentDialog you can call AddDialog() within your constructor.' (captured in ExceptionHandlingMiddleware)
System.ArgumentException: DialogContext.BeginDialogAsync(): A dialog with an id of 'Restart' wasn't found. The dialog must be included in the current or parent DialogSet. For example, if subclassing a ComponentDialog you can call AddDialog() within your constructor.
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.ReplaceDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ReplaceDialog.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginActionAsync(DialogContext dc, Int32 offset, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.OnNextActionAsync(DialogContext dc, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.ResumeDialogAsync(DialogContext dc, DialogReason reason, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.EndDialogAsync(Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.SetProperty.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginActionAsync(DialogContext dc, Int32 offset, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.ReplaceDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.SwitchCondition.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginActionAsync(DialogContext dc, Int32 offset, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.OnNextActionAsync(DialogContext dc, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.ResumeDialogAsync(DialogContext dc, DialogReason reason, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.EndDialogAsync(Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.ReplaceDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.SwitchCondition.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginActionAsync(DialogContext dc, Int32 offset, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.OnNextActionAsync(DialogContext dc, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.ResumeDialogAsync(DialogContext dc, DialogReason reason, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.EndDialogAsync(Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.OnEndOfActionsAsync(DialogContext dc, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.OnNextActionAsync(DialogContext dc, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.ResumeDialogAsync(DialogContext dc, DialogReason reason, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.EndDialogAsync(Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.SetProperty.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginActionAsync(DialogContext dc, Int32 offset, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.ReplaceDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.IfCondition.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginActionAsync(DialogContext dc, Int32 offset, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.OnNextActionAsync(DialogContext dc, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.ResumeDialogAsync(DialogContext dc, DialogReason reason, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.EndDialogAsync(Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.TraceActivity.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginActionAsync(DialogContext dc, Int32 offset, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.OnNextActionAsync(DialogContext dc, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.ResumeDialogAsync(DialogContext dc, DialogReason reason, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.EndDialogAsync(Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.SetProperty.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginActionAsync(DialogContext dc, Int32 offset, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.OnNextActionAsync(DialogContext dc, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.ResumeDialogAsync(DialogContext dc, DialogReason reason, Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.EndDialogAsync(Object result, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.SetProperty.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginActionAsync(DialogContext dc, Int32 offset, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.ReplaceDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.IfCondition.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginActionAsync(DialogContext dc, Int32 offset, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Actions.ActionScope.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.ContinueActionsAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.ContinueDialogAsync(DialogContext dc, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogExtensions.InnerRunAsync(ITurnContext turnContext, String dialogId, DialogContext dialogContext, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogExtensions.InternalRunAsync(ITurnContext turnContext, String dialogId, DialogContext dialogContext, DialogStateManagerConfiguration stateConfiguration, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogExtensions.InternalRunAsync(ITurnContext turnContext, String dialogId, DialogContext dialogContext, DialogStateManagerConfiguration stateConfiguration, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogExtensions.RunAsync(Dialog dialog, ITurnContext turnContext, IStatePropertyAccessor`1 accessor, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialogBot.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
   at BotComponents.ProactiveMessaging.Middleware.ProactiveMessagingMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
   at BotComponents.ActivityLogger.Middleware.ActivityLoggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
   at BotComponents.LocaleSelection.Middleware.LocaleSelectionMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
   at BotComponents.ExceptionMessages.Middleware.ExceptionHandlingMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)

**Comment by a-b-r-o-w-n** [comment]
@Clooney24 I have reached out to the SDK engineers about that PR. There is no update as of now.

**Comment by mrivera-ms** [comment]
The [PR 5656 (dotnet) ](https://github.com/microsoft/botbuilder-dotnet/pull/5656) has been merged and will be available in the next release.
