### ISSUE TITLE
Not able to capture Composer telemetry with Application Insights

### ISSUE THREAD

**Issue by mansirusiaofc** [microsoft/BotFramework-Composer#9555]
When I enable the application insight with Bot Composer and set log personal information and logActivities to true, I can see in Application Insight log Custom Events...there is only activity data no "BotMessageReceived","BotMessageSend","QNA" or "LUIS" also inside custom dimension, "additional properties" and "answers" are not available, I'm not able to collect luis or qna data as in the document:
https://learn.microsoft.com/en-us/composer/how-to-capture-telemetry?tabs=v2x

How can I enable LUIS Results and QnA Maker result in the telemetry data?

**Comment by anishprasad01** [comment]
Hi @mansirusiaofc,

I am unable to reproduce this. I deployed a Composer bot with Application Insights to Azure and was able to see items such as `BotMessageReceived`. 

When you configured Application Insights in Composer, did you make sure to add your Connection String, as shown in the below screenshot? I do not believe that Composer will auto-fill this field for you.

<img width="520" alt="image" src="https://user-images.githubusercontent.com/33945547/231562035-cde96c04-8f45-49d3-8cc9-8ab71b2b4dc2.png">

**Comment by anishprasad01** [comment]
Closing this issue due to inactivity.

**Comment by mansirusiaofc** [comment]
We have already tried this but still answers are not coming.
![Capturetelem](https://user-images.githubusercontent.com/130547794/234497522-b7b04e9c-e249-4da2-b171-73bb23970d28.PNG)

**Comment by mansirusiaofc** [comment]
We are still not getting the result, is there any other configuration we need to change?

**Comment by anishprasad01** [comment]
Have you modified the App Insights settings, and is the bot itself deployed?

**Comment by mansirusiaofc** [comment]
Yes, the bot is deployed, and can you please clarify what modification does App Insights needs we are following this documentation https://learn.microsoft.com/en-us/composer/how-to-capture-telemetry?tabs=v2x so we are just calling custom events.

**Comment by anishprasad01** [comment]
I was simply clarifying whether you made any modifications to App Insights. I followed this exact document and was unable to reproduce your problem.

**Comment by anishprasad01** [comment]
Do you have permissions in Azure to log or access the App Insights data? Following the same docs exactly, I cannot reproduce the issue.

**Comment by arslanafzalch** [comment]
For anyone facing this issue telemetry logs or logs to the console are not logging in Application Insights. 
Go to configuration, and on top switch to "advance settings view"
Now find a section named "telemetry". in "connectionString" Add a connection string copy from Application Insights.

Note: Note that only the instrument key puts a complete connection string.
